---
- name: Install git
  become: true
  ansible.builtin.package:
    name: git
    state: present
- name: NGINX | Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present
  notify: Start-nginx
- name: Create nginx config
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Reload-nginx
- name: Download lighthouse
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: "{{ lighthous_local_dir }}"
- name: Create lighthouse config
  become: true
  ansible.builtin.template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify: Reload-nginx
  tags:
    - lighthouse
    - distr
