---
- name: Install Clickhouse and vector
  hosts: clickhouse-01
  become: true
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
   
  tasks:
    - name: Download distrib
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
            mode: "0644"
            owner: ansible-user
          with_items: "{{ clickhouse_packages }}"
        - name: Get clickhouse distrib common-static
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
            mode: "0644"
            owner: ansible-user
      tags:
        - clickhouse
        - distr
    - name: Install clickhouse packages
      become: true
      ansible.builtin.package:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
        disable_gpg_check: true
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
      tags:
        - clickhouse
        - db
    
- name: Install Vector
  hosts: vector-01
  become: true
  handlers:
    - name: Restart vector service
      ansible.builtin.service:
        name: vector
        state: restarted
      tags:
        - vector
        - restartservice
  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.49.0/vector-0.49.0-1.x86_64.rpm"
        dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
        mode: "0644"
        owner: ansible-user
    - name: Install vector packages
      ansible.builtin.package:
        name:
          - vector-{{ vector_version }}-1.x86_64.rpm
        disable_gpg_check: true
    - name: Create Vector config directory
      ansible.builtin.file:
        path: /etc/vector
        state: directory
        mode: "0755"
        owner: ansible-user
    - name: Deploy Vector config
      ansible.builtin.template:
        src: ./templates/vector.yml.j2
        dest: "{{ vector_config_path }}"
        mode: "0644"
        owner: ansible-user
      notify: Restart vector service
    - name: Ensure Vector is running
      ansible.builtin.service:
        name: vector
        state: started
        enabled: true
